---
title: "Exploratory Data Analysis"
author: "Jiashu Liu, Jingdan Zou & Qihan Chen"
date: "Spring 2023"
output: 
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#library
library(tidyverse)
library(psych)
```


```{r data, include=FALSE}
# load data
NSDUH_2021 <- read.csv("/Users/zjd/Desktop/nyu/Messy data ML/Final/Messy_Data_Final/NSDUH_2021.csv")
```


```{r}
# Select variables according to lasso model
NSDUH_selected <- NSDUH_2021 %>% 
  select(age, race, marital, degree, employ, family, covid_mh, income, bmi, SUD_MJ) %>% 
  mutate(age = as.factor(age),
         race = as.factor(race),
         marital = as.factor(marital), 
         degree = as.factor(degree), 
         employ = as.factor(employ), 
         family = as.factor(family), 
         covid_mh = as.factor(covid_mh), 
         income = as.factor(income), 
         SUD_MJ = as.factor(SUD_MJ))

# remove na from dataset
NSDUH_selected <- na.omit(NSDUH_selected)

# check na
NSDUH_selected %>% summarise_all(list(name = ~sum(is.na(.))/length(.)))
```


## Exploratory Analysis

### descriptive statistics

```{r categorical_v}
summary(NSDUH_selected)
```

### Correlation 

We can examine the correlation among the key study variables according to following Table.

```{r corr, include=FALSE}
corstarsl <- function(x){ 
  require(Hmisc) 
  x <- as.matrix(x) 
  R <- rcorr(x)$r 
  p <- rcorr(x)$P
  # define notions for significance levels; spacing is important.
  mystars <- ifelse(p < .001, "***", ifelse(p < .01, "** ", ifelse(p < .05, "* ", " ")))
  # trunctuate the matrix that holds the correlations to two decimal
  R <- format(round(cbind(rep(-1.11, ncol(x)), R), 2))[,-1] 
  # build a new matrix that includes the correlations with their apropriate stars 
  Rnew <- matrix(paste(R, mystars, sep=""), ncol=ncol(x)) 
  diag(Rnew) <- paste(diag(R), " ", sep="") 
  rownames(Rnew) <- colnames(x) 
  colnames(Rnew) <- paste(colnames(x), "", sep="") 
  # remove upper triangle
  Rnew <- as.matrix(Rnew)
  Rnew[upper.tri(Rnew, diag = TRUE)] <- ""
  Rnew <- as.data.frame(Rnew) 
  # remove last column and return the matrix (which is now a data frame)
  Rnew <- cbind(Rnew[1:length(Rnew)-1])
  return(Rnew) 
}
```

```{r corr_tbl, message=FALSE}
# correlation matrix
knitr::kable(corstarsl(NSDUH_selected))
```


### Visualization

**Age** 
```{r, fig.dim=c(5,3), out.width="70%", fig.align = 'center'}
NSDUH_selected %>% ggplot(
  aes(x = factor(age, levels = 1:4, labels = c("Adolescent", "Young Adult", "Middle Age",
                                               "Elderly")), fill = factor(SUD_MJ))) +
  geom_bar(alpha = 0.5, position = "dodge") +
  scale_fill_manual(values = c("#619CFF", "#FF595E"),name = "SUD_MJ") +
  labs(x = "age", y = "Count") +
  ggtitle("Counts of Age by Marijuana Use Disorder") +
  theme_minimal()
```


**Race**
```{r, fig.dim=c(5,3), out.width="70%", fig.align = 'center'}
NSDUH_selected %>% ggplot(
  aes(x = factor(race, levels = 1:3, labels = c("White", "Non-white", "Hispanic")),
      fill = factor(SUD_MJ))) +
  geom_bar(alpha = 0.5, position = "dodge") +
  scale_fill_manual(values = c("#619CFF", "#FF595E"),name = "SUD_MJ") +
  labs(x = "Race", y = "Count") +
  ggtitle("Count of Race by Marijuana Use Disorder") +
  theme_minimal()
```


**Marital**
```{r, fig.dim=c(5,3), out.width="70%", fig.align = 'center'}
NSDUH_selected %>% ggplot(
  aes(x = factor(marital, levels = 0:2, labels = c("Never married", "Married", 
                                                   "Widowed/Divorced")), fill = factor(SUD_MJ))) +
  geom_bar(alpha = 0.5, position = "dodge") +
  scale_fill_manual(values = c("#619CFF", "#FF595E"),name = "SUD_MJ") +
  labs(x = "Marital", y = "Count") +
  ggtitle("Count of Marital by Marijuana Use Disorder") +
  theme_minimal()
```


**Degree**
```{r, fig.dim=c(5,3), out.width="70%", fig.align = 'center'}
NSDUH_selected %>% ggplot(
  aes(x = factor(degree, levels = 1:3, labels = c("w/o high school", "High school degree", 
                                                   "Higher")), fill = factor(SUD_MJ))) +
  geom_bar(alpha = 0.5, position = "dodge") +
  scale_fill_manual(values = c("#619CFF", "#FF595E"),name = "SUD_MJ") +
  labs(x = "Degree", y = "Count") +
  ggtitle("Count of Degree by Marijuana Use Disorder") +
  theme_minimal()
```


**Employ**
```{r, fig.dim=c(5,3), out.width="70%", fig.align = 'center'}
NSDUH_selected %>% ggplot(
  aes(x = factor(employ, levels = 1:4, labels = c("Full time", "Part time", 
                                                   "Unemployed", "Other")), 
      fill = factor(SUD_MJ))) +
  geom_bar(alpha = 0.5, position = "dodge") +
  scale_fill_manual(values = c("#619CFF", "#FF595E"),name = "SUD_MJ") +
  labs(x = "Employ", y = "Count") +
  ggtitle("Count of Employ by Marijuana Use Disorder") +
  theme_minimal()
```


**Family**
```{r, fig.dim=c(5,3), out.width="70%", fig.align = 'center'}
NSDUH_selected %>% ggplot(
  aes(x = factor(family, levels = 1:6, 
                 labels = c(1:5, "6 or more people in household")), 
      fill = factor(SUD_MJ))) +
  geom_bar(alpha = 0.5, position = "dodge") +
  scale_fill_manual(values = c("#619CFF", "#FF595E"),name = "SUD_MJ") +
  labs(x = "Family Size", y = "Count") +
  ggtitle("Count of Family Size by Marijuana Use Disorder") +
  theme_minimal()
```


**Levels for Covid negatively affected mental health**
```{r, fig.dim=c(5,3), out.width="70%", fig.align = 'center'}
NSDUH_selected %>% ggplot(
  aes(x = factor(covid_mh, levels = 0:3, labels = c("Otherwise", "Not at all", 
                                                   "A little", "Lot")), fill = factor(SUD_MJ))) +
  geom_bar(alpha = 0.5, position = "dodge") +
  scale_fill_manual(values = c("#619CFF", "#FF595E"),name = "SUD_MJ") +
  labs(x = "Levels for Covid negatively affected mental health", y = "Count") +
  ggtitle("Covid x Mental Health by Marijuana Use Disorder") +
  theme_minimal()
```

**Income**
```{r, fig.dim=c(5,3), out.width="70%", fig.align = 'center'}
NSDUH_selected %>% ggplot(
  aes(x = factor(income, levels = 0:3, labels = c("Otherwise", "Not at all", 
                                                   "A little", "Lot")), fill = factor(SUD_MJ))) +
  geom_bar(alpha = 0.5, position = "dodge") +
  scale_fill_manual(values = c("#619CFF", "#FF595E"),name = "SUD_MJ") +
  labs(x = "Family Income", y = "Count") +
  ggtitle("Count of Family Income by Marijuana Use Disorder") +
  theme_minimal()
```


**BMI**
```{r, fig.dim=c(5,3), out.width="70%", fig.align = 'center'}
NSDUH_selected %>% ggplot(
  aes(x = bmi, fill = factor(SUD_MJ))) +
  geom_histogram(alpha = 0.5, position = "identity", bins = 20)  +
  scale_fill_manual(values = c("#619CFF", "#FF595E"),name = "SUD_MJ") +
  labs(x = "BMI", y = "Count") +
  ggtitle("Count of BMI by Marijuana Use Disorder") +
  geom_vline(xintercept = mean(NSDUH_selected$bmi), color = "red", linetype = "dashed") +
  theme_minimal()
```


