---
title: "model"
author: "CHEN QIHAN"
date: "2023-05-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, include=FALSE}
library(tidyverse)
library(dplyr)
library(ROCR)
library(ranger)

set.seed(123)
```

```{r}
# load data
NSDUH_2021 <- read.csv("NSDUH_2021.csv")

# drop all NAs in important predictor variables
NSDUH_2021 <- NSDUH_2021[complete.cases(NSDUH_2021$age, NSDUH_2021$race,
                                        NSDUH_2021$marital, NSDUH_2021$degree,
                                        NSDUH_2021$employ, NSDUH_2021$family,
                                        NSDUH_2021$covid_mh, NSDUH_2021$income,
                                        NSDUH_2021$bmi), ]

# make variables as factors
NSDUH_2021 <- NSDUH_2021 %>% 
  mutate(age = as.factor(age), race = as.factor(race), marital = as.factor(marital),
         degree = as.factor(degree), employ = as.factor(employ), 
         family = as.factor(family), covid_mh = as.factor(covid_mh),
         income = as.factor(income))
```

```{r}
# find split_size to divide data in 67% train/ 33% test sets
split_size <- sample(1:nrow(NSDUH_2021), floor(0.67 * nrow(NSDUH_2021)))

# Extract the train and test sets
train <- NSDUH_2021[split_size, ]
test <- NSDUH_2021[-split_size, ]
```

```{r}
# fit a logistic regression model on train
logi_model <- glm(SUD_MJ ~ age + race + marital + degree + employ +
                     family + covid_mh + income + bmi, 
                  data = train, family = binomial(link = "logit"))
summary(logi_model)

# compute the AUC of logi model on test
test <- test %>% 
  mutate(logi.prob = predict(logi_model, newdata = test, type = 'response'))
test.logi.pred <- prediction(test$logi.prob, test$SUD_MJ)
test.logi.perf <- performance(test.logi.pred, "auc")
cat('The AUC score of the logistic regression model on test is ', 
    test.logi.perf@y.values[[1]], "\n")

```


```{r}
# fit a random forest model on train
rf_model <- ranger(SUD_MJ ~ age + race + marital + degree + employ +
                     family + covid_mh + income + bmi,
                   data = train, num.trees = 1000, 
                   respect.unordered.factors = TRUE, probability = TRUE)
summary(rf_model)

# compute the AUC of rf model on test
test <- test %>%
  mutate(rf.prob = predict(rf_model, data = test)$predictions[,2])
test.rf.pred <- prediction(test$rf.prob, test$SUD_MJ)
test.rf.perf <- performance(test.rf.pred, "auc")
cat('The AUC score of the random forest model on test is', 
    test.rf.perf@y.values[[1]], "\n")
```

```{r}
# Create one plot with two precision-at-k curves (one for each model)
# first, create a data frame with x-value and y-value for each model
logi.plot.data <- test %>% 
  arrange(desc(logi.prob)) %>% 
  mutate(nums = row_number(), 
         precision = cumsum(SUD_MJ) / sum(SUD_MJ),
         perc = nums/n(),
         model = "logistic model") %>% 
  select(perc, precision, model)

rf.plot.data <- test %>% 
  arrange(desc(rf.prob)) %>% 
  mutate(nums = row_number(),
         precision = cumsum(SUD_MJ) / sum(SUD_MJ),
         perc = nums/n(),
         model = "random forest model") %>% 
  select(perc, precision, model)

# then, combine 2 data frames by row
plot.data <- rbind(logi.plot.data, rf.plot.data)

# draw and save the plot
theme_set(theme_bw())
p <- ggplot(data = plot.data, aes(x = perc, y = precision, color = factor(model))) + 
  geom_line() +
  ggtitle("Recall-at-k% plot") +
  scale_x_log10('\nPercent of Marijuana', limits=c(0.003, 1), 
                breaks=c(.003,.01,.03,.1,.3,1),
                labels=c('0.3%','1%','3%','10%','30%','100%')) +
  scale_y_continuous("Recall", limits=c(0, 1), labels=scales::percent)
p

# ggsave(plot=p, file="./recall_at_k_plot.png", height = 5, width = 10)
```
